#!/usr/bin/env python3

from PyQt5.QtWidgets import QApplication, \
    QMainWindow, QWidget, QPushButton, QVBoxLayout, \
    QLabel, QSlider, QHBoxLayout

from PyQt5.QtCore import Qt

class SliderDisplay(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        self.setWindowTitle('Slider')

        # A widget to hold everything
        widget = QWidget()
        self.setCentralWidget(widget)
        self.setGeometry(100, 100, 300, 100)  # set size

        # A layout
        layout = QHBoxLayout()
        widget.setLayout(layout)

        # Slider
        self.slider = QSlider(Qt.Horizontal)
        self.slider.setTickPosition(QSlider.TicksAbove)
        self.slider.setMinimum(0)
        self.slider.setMaximum(10)
        self.slider.setTickInterval(1)
        self.slider.valueChanged.connect(self.slider_val)

        # label
        self.label1 = QLabel()
        self.slider_val()

        # You probably want to add in other interface elements here

        # Add things to the layout
        layout.addWidget(self.label1)
        layout.addWidget(self.slider)

        # Add other widgets to the layout here.  Possibly other layouts.

    def slider_val(self):
        val = self.slider.value()
        # val /= 10
        words = 'foo: '+str(val)
        self.label1.setText(words)

if __name__ == '__main__':

    app = QApplication([])

    window = SliderDisplay()

    window.show()

    app.exec_()

