#!/usr/bin/env python3


from PyQt5.QtWidgets import QApplication, \
    QMainWindow, QWidget, QPushButton, QVBoxLayout, \
    QLabel, QSlider

from PyQt5.QtCore import Qt


class Interface(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        self.setWindowTitle('slidertest2')

        # A widget to hold everything
        widget = QWidget()
        self.setCentralWidget(widget)
        self.setGeometry(100, 100, 200, 200)   # set size

        # A layout
        layout = QVBoxLayout()
        widget.setLayout(layout)

        # Slider
        self.slider = QSlider(Qt.Horizontal)
        self.slider.setTickPosition(QSlider.TicksAbove)
        self.slider.setMinimum(0)
        self.slider.setMaximum(10)
        self.slider.setTickInterval(1)
        self.slider.valueChanged.connect(self.slider_val)

        # label
        self.label1 = QLabel()
        self.slider_val()

        # Quit button
        quit_button = QPushButton('Quit')
        quit_button.clicked.connect(app.exit)

        # You probably want to add in other interface elements here

        # Add things to the layout
        layout.addWidget(self.label1)
        layout.addWidget(quit_button)
        layout.addWidget(self.slider)

        # Add other widgets to the layout here.  Possibly other layouts.
    def slider_val(self):
        val = self.slider.value()
        val /= 10
        self.label1.setText(str(val))


if __name__ == '__main__':
    app = QApplication([])

    interface = Interface()

    interface.show()

    app.exec_()

