#!/usr/bin/env python3\

# python D:\PythonScripts\499hw2\directory.py
import urllib.request, sys

# returns the string from html
def getstring(url):
    buffer = urllib.request.urlopen(url)
    string = str(buffer.read().decode('utf-8'))
    return string

# make the first letter of string upper case
def firstupper(element):
    element = list(element)
    element[0] = element[0].upper()
    element = ''.join(element)
    return element

# this function will construct the url(s) based on cmd input
def makeurl():
    first = []
    last = []
    URL = []
    # construct first and last arrays
    if len(sys.argv) != 1:  # if there are input arguments
        for i in range(1,len(sys.argv)):
            if i % 2 != 0: # odd index arguments are first names
                first.append(firstupper(sys.argv[i]))

            elif i % 2 == 0:  # even index arguments are last names
                last.append(firstupper(sys.argv[i]))

    else:  # if no input arguments
        print("No input arguments provided!")

    # construct search url
    for i in range(0,len(first)):
        URL.append('http://directory.oregonstate.edu/?type=search&cn=' + first[i] + '+' + last[i])

    return URL
if __name__ == '__main__':

    listurl = makeurl()

    content = getstring(listurl[1])  # get the string from html

    person = {}  # empty dictionary for dude

    for i, line in enumerate(content.split('<dd>')):
        if i == 1:  # name
            name = line.split('</dd')[0]
        if i == 3:
            title = line.split('</dd')[0]
        if i == 4:
            dept = line.split('</dd')[0]
        if i == 5:
            phone = line.split('"tel:')[1].split('"')[0]
            # phone = line.split('</dd')[0]

    print("Name:", name)
    print("Title:", title)
    print("Department:", dept)
    print("Phone:", phone)

# this code currently doesn't defend against random inputs. As in you can type in
# James Franco and it will go to an error.
