#!/usr/bin/env python3\

# python D:\PythonScripts\499hw2\directory.py
import urllib.request, sys

def getstring(url):
    buffer = urllib.request.urlopen(url)
    string = str(buffer.read().decode('utf-8'))
    return string


if __name__ == '__main__':

    if len(sys.argv) != 1:  # if there are input arguments

        first = sys.argv[1]
        last = sys.argv[2]

    else:

        print("No input arguments provided!")

    first = list(first)
    first[0] = first[0].upper()
    first = ''.join(first)

    last = list(last)
    last[0] = last[0].upper()
    last = ''.join(last)
    # construct search url
    url = 'http://directory.oregonstate.edu/?type=search&cn=' + first + '+' + last
    content = getstring(url)  # get the string from html

    person = {}  # empty dictionary for dude

    for i, line in enumerate(content.split('<dd>')):
        if i == 1:  # name
            name = line.split('</dd')[0]
        if i == 3:
            title = line.split('</dd')[0]
        if i == 4:
            dept = line.split('</dd')[0]
        if i == 5:
            phone = line.split('"tel:')[1].split('"')[0]
            # phone = line.split('</dd')[0]

    print("Name:", name)
    print("Title:", title)
    print("Department:", dept)
    print("Phone:", phone)

# this code currently doesn't defend against random inputs. As in you can type in
# James Franco and it will go to an error.
