#!/usr/bin/env python3

import urllib.request, 
if __name__ == '__main__':

    # This is 2010 census data for LA
    with urllib.request.urlopen('https://data.lacity.org/api/views/nxs9-385f/rows.json') as url:
        data = json.loads(url.read().decode())
        print(data['meta']['view']['name'])

        for column in data['meta']['view']['columns']:
            print(' ', column['name'])

        # Zip codes and total population
        total = 0
        for datum in data['data']:
            total += int(datum[-6])
            print('{0}: {1}'.format(datum[-7], datum[-6]))

        print('{0:,} people lived in LA in 2010'.format(total))
